import { useState } from 'react'
import { detectWatermark, type DetectResponse } from '../api/client'
import ScoreBar from '../components/ScoreBar'
import { Search, AlertCircle, Info } from 'lucide-react'

const EXAMPLE_TEXTS = [
  "The history of artificial intelligence began in antiquity, with myths, stories and rumors of artificial beings endowed with intelligence or consciousness by master craftsmen. As Pamela McCorduck writes, AI began with an ancient wish to forge the gods.",
  "Climate change presents one of the greatest challenges facing humanity today because its effects are both far-reaching and deeply interconnected. Rising global temperatures are causing shifts in weather patterns, melting polar ice caps, and raising sea levels around the world.",
]

export default function Detector() {
  const [text, setText] = useState('')
  const [result, setResult] = useState<DetectResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const detect = async () => {
    if (!text.trim()) return
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      const res = await detectWatermark(text)
      setResult(res)
    } catch (e: unknown) {
      const msg = (e as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      setError(msg ?? 'Could not reach the API. Is the backend server running?')
    } finally {
      setLoading(false)
    }
  }

  const wordCount = text.trim().split(/\s+/).filter(Boolean).length

  return (
    <div className="space-y-6 max-w-2xl">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-white">Watermark Detector</h2>
        <p className="text-slate-400 mt-1 text-sm">
          Paste any LLM-generated text to score it against both watermarking algorithms.
        </p>
      </div>

      {/* Info banner */}
      <div className="flex gap-3 bg-indigo-950/50 border border-indigo-800/50 rounded-xl p-4 text-sm text-indigo-300">
        <Info size={16} className="shrink-0 mt-0.5" />
        <p>
          Detection uses the same secret keys as generation — so only text generated by{' '}
          <span className="font-mono">main.py</span> will show positive z-scores. Longer
          texts (&gt;100 tokens) give more reliable readings.
        </p>
      </div>

      {/* Textarea */}
      <div className="space-y-2">
        <div className="flex items-center justify-between text-xs text-slate-500">
          <span>Input text</span>
          <span>{wordCount} words</span>
        </div>
        <textarea
          className="w-full h-44 bg-slate-800 border border-slate-700 rounded-xl p-4 text-slate-200 text-sm placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-600 resize-none transition-colors"
          placeholder="Paste generated text here…"
          value={text}
          onChange={e => setText(e.target.value)}
        />

        {/* Example buttons */}
        <div className="flex gap-2 flex-wrap">
          {EXAMPLE_TEXTS.map((t, i) => (
            <button
              key={i}
              onClick={() => setText(t)}
              className="text-xs px-2.5 py-1 rounded-md bg-slate-700 hover:bg-slate-600 text-slate-400 hover:text-white transition-colors"
            >
              Example {i + 1}
            </button>
          ))}
        </div>
      </div>

      {/* Detect button */}
      <button
        onClick={detect}
        disabled={loading || text.trim().length < 20}
        className="w-full py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 disabled:opacity-40 disabled:cursor-not-allowed text-white font-semibold flex items-center justify-center gap-2 transition-colors"
      >
        <Search size={17} />
        {loading ? 'Analysing…' : 'Detect Watermark'}
      </button>

      {/* Error */}
      {error && (
        <div className="flex gap-3 bg-red-950/50 border border-red-800/50 rounded-xl p-4 text-red-400 text-sm">
          <AlertCircle size={16} className="shrink-0 mt-0.5" />
          {error}
        </div>
      )}

      {/* Results */}
      {result && (
        <div className="space-y-4">
          <div className="flex items-center gap-2 text-sm text-slate-400">
            <span className="bg-slate-700 rounded-md px-2 py-0.5 text-white font-mono">
              {result.token_count}
            </span>
            tokens analysed
          </div>

          {/* STA-1 card */}
          <ResultCard
            name="STA-1"
            subtitle="Green/Red-list — Kirchenbauer et al. 2023"
            algo={result.sta1}
            color="indigo"
          />

          {/* SynthID card */}
          <ResultCard
            name="SynthID-Text"
            subtitle="Tournament sampling — Dathathri et al. 2024"
            algo={result.synthid}
            color="cyan"
          />
        </div>
      )}
    </div>
  )
}

// ── Sub-component ──────────────────────────────────────────────────────

interface ResultCardProps {
  name: string
  subtitle: string
  algo: DetectResponse['sta1']
  color: 'indigo' | 'cyan'
}

function ResultCard({ name, subtitle, algo, color }: ResultCardProps) {
  const detected = algo.detected
  const accentText = color === 'indigo' ? 'text-indigo-400' : 'text-cyan-400'
  const borderColor = color === 'indigo' ? 'border-indigo-700/40' : 'border-cyan-700/40'

  return (
    <div className={`bg-slate-800 rounded-xl p-5 border ${borderColor} space-y-4`}>
      <div className="flex items-start justify-between gap-2">
        <div>
          <p className={`font-semibold text-base ${accentText}`}>{name}</p>
          <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>
        </div>
        <span
          className={`shrink-0 text-xs font-bold px-3 py-1 rounded-full ${
            detected
              ? 'bg-emerald-900/60 text-emerald-400 border border-emerald-700/40'
              : 'bg-slate-700 text-slate-400'
          }`}
        >
          {detected ? '✓ DETECTED' : '○ NOT DETECTED'}
        </span>
      </div>

      <ScoreBar value={algo.z_score} threshold={algo.threshold} color={color} />
    </div>
  )
}
