"""
SynthID-Text Watermark Detector

Detects the tournament-sampling watermark generated by
:class:`SynthIDWatermark`.

Detection procedure
-------------------
For each token x_t  (t ≥ 1) in the candidate text:

  g_t = score_token(x_t, context_tokens_t)
      = (1/D) Σ_{d=0}^{D-1}  hash(k_d, x_{t-d-1}, x_t)   ∈ [0, 1]

Under H₀ (no watermark): each g_t ~ Uniform(0,1)  ⟹  E[g_t] = 0.5,
  Var[g_t] = 1/12.

For N tokens:  mean_g ~ N(0.5, 1/(12N))

z = (mean_g − 0.5) / (1 / √(12N))  =  √(12N) · (mean_g − 0.5)

Under the watermark, tournament selection biases the sampled tokens
towards high-scoring candidates, so mean_g > 0.5 and z > 0.
"""

from __future__ import annotations

import math
from typing import List, Tuple, Union

import numpy as np
import torch
from scipy import stats

from .base_detector import BaseDetector
from ..watermarking.synthid_watermark import SynthIDWatermark


class SynthIDDetector(BaseDetector):
    """
    Detects the SynthID-Text tournament-sampling watermark.

    Parameters
    ----------
    watermark : SynthIDWatermark
        Must share the same *keys* as used during generation.
    z_threshold : float
        Detection threshold on the z-score.  Default 4.0 is consistent
        with :class:`STA1Detector` and gives FPR ≈ 3 × 10⁻⁵.
    """

    def __init__(
        self, watermark: SynthIDWatermark, z_threshold: float = 4.0
    ) -> None:
        self.watermark = watermark
        self.z_threshold = z_threshold

    # ------------------------------------------------------------------
    def _compute_g_values(self, ids: list) -> List[float]:
        """Return the per-token g-values for positions 1 … len(ids)-1."""
        g_vals: List[float] = []
        for t in range(1, len(ids)):
            ctx = ids[max(0, t - self.watermark.depth): t]
            g = self.watermark.score_token(ids[t], ctx)
            g_vals.append(g)
        return g_vals

    # ------------------------------------------------------------------
    def score(self, token_ids: Union[torch.Tensor, list]) -> float:
        """
        Compute the z-score for *token_ids*.

        A z-score above :attr:`z_threshold` indicates the text is
        (likely) watermarked.
        """
        ids = self._to_list(token_ids)
        g_vals = self._compute_g_values(ids)
        n = len(g_vals)
        if n == 0:
            return 0.0

        mean_g = float(np.mean(g_vals))
        # std of the mean under H₀ (uniform individual g-values)
        std_null = math.sqrt(1.0 / (12.0 * n))
        if std_null == 0.0:
            return 0.0

        return (mean_g - 0.5) / std_null

    # ------------------------------------------------------------------
    def get_mean_g(self, token_ids: Union[torch.Tensor, list]) -> float:
        """Return the raw mean g-value (easier to interpret than z-score)."""
        ids = self._to_list(token_ids)
        g_vals = self._compute_g_values(ids)
        return float(np.mean(g_vals)) if g_vals else 0.5

    # ------------------------------------------------------------------
    def detect(self, token_ids: Union[torch.Tensor, list]) -> Tuple[bool, float]:
        """
        Returns
        -------
        (is_watermarked, z_score)
        """
        z = self.score(token_ids)
        return z >= self.z_threshold, z

    # ------------------------------------------------------------------
    def get_p_value(self, token_ids: Union[torch.Tensor, list]) -> float:
        """One-tailed p-value for the z-test."""
        return float(1.0 - stats.norm.cdf(self.score(token_ids)))

    def get_name(self) -> str:
        return "SynthID Detector"
